// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eAgenda.WebApp.Compartilhado.Infra.Orm;

#nullable disable

namespace eAgenda.WebApp.Compartilhado.Infra.Orm.Migrations
{
    [DbContext(typeof(EAgendaDbContext))]
    [Migration("20260714232738_Add_TBContato")]
    partial class Add_TBContato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eAgenda.WebApp.ModuloContato.Dominio.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK_TBContato");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBContato_Email");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("UQ_TBContato_Telefone");

                    b.ToTable("TBContato", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
